# Generated by Django 3.2.9 on 2021-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20211115_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
