# Generated by Django 3.2.9 on 2021-11-15 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20211115_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 15, 19, 39, 32, 470594, tzinfo=utc)),
        ),
    ]
