# Generated by Django 3.2.9 on 2021-11-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_alter_comment_created_on'),
        ('rareapi', '0005_alter_author_created_on'),
    ]

    operations = [
    ]
