# Generated by Django 3.2.9 on 2021-11-15 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0006_merge_20211115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_on',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 15, 20, 19, 28, 880684, tzinfo=utc)),
        ),
    ]
