# Generated by Django 3.2.9 on 2021-11-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_auto_20211115_2029'),
        ('rareapi', '0008_alter_author_created_on'),
    ]

    operations = [
    ]
