# Generated by Django 3.2.9 on 2021-11-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0009_merge_20211115_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
