# Generated by Django 3.2.9 on 2021-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0010_alter_author_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(upload_to='actionimages'),
        ),
    ]
