# Generated by Django 3.2.9 on 2021-11-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0014_alter_comment_post'),
        ('rareapi', '0014_merge_20211117_2131'),
    ]

    operations = [
    ]
